DROP TABLE WHO_REGION
DROP TABLE COUNTRY
DROP TABLE CASE_DATA
DROP TABLE REPORT

CREATE TABLE WHO_REGION(
    REGION_CODE int,
    REGION_NAME VARCHAR(30),
    PRIMARY KEY (REGION_CODE)
);

CREATE TABLE CASE_DATA(
    DATA_ID int,
    CONFIRMED int,
    DEATHS int,
    RECOVERED int,
    ACTIVE int, 
    PRIMARY KEY (Data_Id)
);

CREATE TABLE PROVIDER(
    PROV_ID int,
    PROV_NAME VARCHAR(40),
    PRIMARY KEY (PROV_ID)

);

CREATE TABLE REPORT(
    REPORT_ID int,
    PROV_ID int,
    REPORT_DATE date,
    DATA_ID INT,
    PRIMARY KEY(REPORT_ID, PROV_ID),
    CONSTRAINT FK_DATA_ID FOREIGN KEY (DATA_ID)
        REFERENCES CASE_DATA(DATA_ID)
);

CREATE TABLE COUNTRY(
    COUNTRY_ID int,
    COUNTRY_NAME varchar(35),
    PROV_ID int,
    REGION_CODE int,
    PRIMARY KEY (REGION_CODE, COUNTRY_ID),
    CONSTRAINT FK_REGION_CODE FOREIGN KEY (REGION_CODE)
        REFERENCES WHO_REGION(REGION_CODE),
    CONSTRAINT FK_PROVIDER_ID FOREIGN KEY (PROV_ID)
        REFERENCES PROVIDER(PROV_ID)
    

);


