# -*- coding: utf-8 -*-
"""Preprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17fLF9ueA1I7L5gXAkmVKTm_F2k2s_3EQ
"""

import pandas as pd
import re

import pandas as pd
from termcolor import colored

filename = "country_wise_latest.csv"

try:
    # Read CSV directly into DataFrame
    df = pd.read_csv(filename)
    print(colored(f"Loaded {len(df)} chat lines into DataFrame.", "green"))

except FileNotFoundError:
    print(colored(" country_wise_latest.csv not found. Please re-run the download cell.", "red"))
except Exception as e:
    print(colored(f"Error reading file: {e}", "yellow"))

print(df)

#WHO_REGION
dfWHO_REGION = df[['REGION_CODE','REGION_NAME']]
dfWHO_REGION = dfWHO_REGION.drop_duplicates()
dfWHO_REGION.to_csv('dfWHO_REGION.csv', index=False)

#Country
dfCountry = df[['COUNTRY_CODE','REGION_CODE','COUNTRY_NAME','PROV_ID']]
dfCountry.to_csv('dfCountry.csv',index=False)

#Provider
dfProvider = df[['PROV_ID','PROV_NAME']]
dfProvider = dfProvider.drop_duplicates()
dfProvider.to_csv('dfProvider.csv', index=False)

#Report
dfReport = df[['REPORT_ID','PROV_ID','REPORT_DATE','DATA_ID']]

dfReport.to_csv('dfReport.csv', index=False)

#Case_Data
dfCase_Data = df[['DATA_ID','CONFIRMED','DEATHS','RECOVERED','ACTIVE']]
dfCase_Data.to_csv('dfCase_Data.csv', index=False)

